name: CI/CD

on:
  push:
    branches:
      - main
      - master

  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Login to Docker Hub
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        if: github.event_name == 'push'
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        if: github.event_name == 'push'
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/waste-bank-backend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/waste-bank-backend:${{ github.sha }}

      - name: Run Trivy vulnerability scanner
        if: github.event_name == 'push'
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: '${{ secrets.DOCKERHUB_USERNAME }}/waste-bank-backend:${{ github.sha }}'
          scan-type: 'image'
          scanners: 'vuln'
          vuln-type: 'os,library'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'


  deploy:
    name: Deploy to EC2
    needs: test
    if: github.event_name == 'push'

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
          
            cd ~/waste-bank
          
            git fetch origin main
            git reset --hard origin/main
          
            export IMAGE_TAG=${{ github.sha }}
          
            docker compose -f docker-compose.prod.yml pull app
          
            docker compose -f docker-compose.prod.yml up -d app mysql nginx
          
            docker image prune -f
          
            sleep 10
          
            curl -f http://localhost/health
          
            echo "Deployment successful"